version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  build:
    commands:
      - echo "Starting ${BUILD_PHASE} deploy using node $(node --version), yarn $(yarn --version)"
      - ./deploy.sh $BUILD_PHASE
